// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-gWYYO0RN6J-Lkn6GMvIyPDm4vX3Xxng',
    appId: '1:236288544112:web:6c5d0a9771fffbe24fd3b5',
    messagingSenderId: '236288544112',
    projectId: 'arogyasos-c23e6',
    authDomain: 'arogyasos-c23e6.firebaseapp.com',
    storageBucket: 'arogyasos-c23e6.firebasestorage.app',
    measurementId: 'G-H5XLB8S09H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAes1SXVSo30NXtMK6tlht03QsVIcuo1kk',
    appId: '1:236288544112:android:ef93e6b2d96322014fd3b5',
    messagingSenderId: '236288544112',
    projectId: 'arogyasos-c23e6',
    storageBucket: 'arogyasos-c23e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1eBLZ0UMI87yIzCYk-MqqBSW-0DDbp1A',
    appId: '1:236288544112:ios:ec10574adcedb2134fd3b5',
    messagingSenderId: '236288544112',
    projectId: 'arogyasos-c23e6',
    storageBucket: 'arogyasos-c23e6.firebasestorage.app',
    iosBundleId: 'com.example.arogyaSosApp',
  );
}
